{
 "title": "Topological Inventory - Collectors & Operations",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Operations - Up", "type": "text", "gridPos": { "h": 1, "w": 11, "x": 0, "y": 1 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 8, "w": 1, "x": 11, "y": 1 }, "options": { "content": "|" } },
  { "title": "Collectors - Up", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 12, "y": 1 }, "options": { "content": " " } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=~\"topological-inventory.amazon-operations\"})",
     "legendFormat": "Amazon"
    },
    {
     "expr": "sum(up{service=~\"topological-inventory.ansible-tower-operations\"})",
     "legendFormat": "Ansible Tower"
    },
    {
     "expr": "sum(up{service=~\"topological-inventory.azure-operations\"})",
     "legendFormat": "Azure"
    },
    {
     "expr": "sum(up{service=~\"topological-inventory.openshift-operations\"})",
     "legendFormat": "OpenShift"
    },
    {
     "expr": "sum(up{service=~\"topological-inventory.satellite-operations\"})",
     "legendFormat": "Satellite"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=~\"service-amazon.*\",pod=~\"collector-amazon-.*\"})",
     "legendFormat": "Amazon"
    },
    {
     "expr": "sum(up{service=~\"service-ansible-tower.*\",pod=~\"collector-ansible-tower-.*\"})",
     "legendFormat": "Ansible Tower"
    },
    {
     "expr": "sum(up{service=\"topological-ansible-tower-targeted-collector\"})",
     "legendFormat": "Targeted Tower"
    },
    {
     "expr": "sum(up{service=~\"service-azure.*\",pod=~\"collector-azure-.*\"})",
     "legendFormat": "Azure"
    }
   ]
  },
  { "title": "Operations - Restarts Count", "type": "text", "gridPos": { "h": 1, "w": 11, "x": 0, "y": 5 } },
  { "title": "Collectors - Restarts Count", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 12, "y": 5 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-amazon-operations\"}[$__range]))",
     "legendFormat": "Amazon"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-ansible-tower-operations\"}[$__range]))",
     "legendFormat": "Ansible Tower"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-azure-operations\"}[$__range]))",
     "legendFormat": "Azure"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-openshift-operations\"}[$__range]))",
     "legendFormat": "OpenShift"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-satellite-operations\"}[$__range]))",
     "legendFormat": "Satellite"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=~\"collector-amazon-.*\", namespace=~\"topological-inventory-.*\"}[$__range])))",
     "legendFormat": "Amazon"
    },
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=~\"collector-ansible-tower-.*\", namespace=~\"topological-inventory-.*\"}[$__range])))",
     "legendFormat": "Ansible Tower"
    },
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-ansible-tower-targeted-collector\"}[$__range])))",
     "legendFormat": "Targeted Tower"
    },
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=~\"collector-azure-.*\", namespace=~\"topological-inventory-.*\"}[$__range])))",
     "legendFormat": "Azure"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate (container_cpu_usage_seconds_total{container=~\"topological-inventory-.*-operations\"}[1m])",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "rate (container_cpu_usage_seconds_total{container=~\"collector-.*-.*\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"topological-inventory-.*-operations\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"collector-.*-.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Collectors - Amazon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Avg / Max Request Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(topological_inventory_amazon_collector_refresh_time_sum[5m]) / rate(topological_inventory_amazon_collector_refresh_time_count[5m]) > 0)",
     "legendFormat": "Max Request"
    },
    {
     "expr": "avg(rate(topological_inventory_amazon_collector_refresh_time_sum[5m]) / rate(topological_inventory_amazon_collector_refresh_time_count[5m]) > 0)",
     "legendFormat": "Avg Request"
    }
   ]
  },
  {
   "title": "Refresh Duration by Entity Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(topological_inventory_amazon_collector_refresh_time_sum[5m]) / rate(topological_inventory_amazon_collector_refresh_time_count[5m]) * 1000",
     "legendFormat": "{{entity_type}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(topological_inventory_amazon_collector_errors_total[$__range])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Collectors - Azure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg / Max Request Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(rate(topological_inventory_azure_collector_refresh_time_sum[5m]) / rate(topological_inventory_azure_collector_refresh_time_count[5m]) > 0)",
       "legendFormat": "Max Request"
      },
      {
       "expr": "avg(rate(topological_inventory_azure_collector_refresh_time_sum[5m]) / rate(topological_inventory_azure_collector_refresh_time_count[5m]) > 0)",
       "legendFormat": "Avg Request"
      }
     ]
    },
    {
     "title": "Refresh duration by entity type",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_azure_collector_refresh_time_sum[5m]) / rate(topological_inventory_azure_collector_refresh_time_count[5m]) * 1000",
       "legendFormat": "{{entity_type}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_azure_collector_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations - Amazon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_amazon_operations_status_counter[$__range])) by (name, status)",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_amazon_operations_duration_seconds_sum[5m]) / rate(topological_inventory_amazon_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_amazon_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations - Ansible Tower",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_ansible_tower_operations_status_counter[$__range])) by (name, status)",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_ansible_tower_operations_duration_seconds_sum[5m]) / rate(topological_inventory_ansible_tower_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_ansible_tower_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations - Azure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_azure_operations_status_counter[$__range])) by (name, status)",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_azure_operations_duration_seconds_sum[5m]) / rate(topological_inventory_azure_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_azure_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations - OpenShift",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_openshift_operations_status_counter[$__range])) by (name, status)",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_openshift_operations_duration_seconds_sum[5m]) / rate(topological_inventory_openshift_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_openshift_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations - Satellite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_satellite_operations_status_counter[$__range])) by (name, status)",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_satellite_operations_duration_seconds_sum[5m]) / rate(topological_inventory_satellite_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_satellite_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}