{
 "title": "Topological Inventory general",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(topological_inventory_api_http_requests_total,controller)"
   },
   {
    "name": "action",
    "label": "Action",
    "query": "label_values(topological_inventory_api_http_requests_total{controller=~\"$controller\"},action)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Up",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "Restarts count / chosen range",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-api\"})"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-ingress-api\"})"
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-orchestrator\"})"
    }
   ]
  },
  {
   "title": "Persister",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-persister\"})"
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-sources-sync\"})"
    }
   ]
  },
  {
   "title": "Host Inv. Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-host-inventory-sync\"})"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-ingress-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-orchestrator\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Persister",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-persister\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-sources-sync\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Host Inv. Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-host-inventory-sync\"}[$__range])))"
    }
   ]
  },
  { "title": "Alert: 10 restarts/h [TODO]", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 5 } },
  { "title": "Kafka lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Kafka lag - Operations ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=~'platform.topological-inventory.operations-.*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "Kafka lag - !Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=~'platform.topological-inventory..*',topic!~'platform.topological-inventory.operations.*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "Host Inventory Sync [TODO]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events count",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_orchestrator_events_count[$__range])) by (event_name)",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Collectors' OpenShift Resources",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 6, "x": 11, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "topological_inventory_orchestrator_config_maps",
       "legendFormat": "{{source_type}}-ConfigMap"
      },
      {
       "expr": "topological_inventory_orchestrator_deployment_configs",
       "legendFormat": "{{source_type}}-DC"
      },
      {
       "expr": "topological_inventory_orchestrator_secrets",
       "legendFormat": "{{source_type}}-Secret"
      }
     ]
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    { "title": "Related to chosen range", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 5 } },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_errors_total[$__range]))"
      }
     ]
    },
    {
     "title": "Sources Created ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_sources_created[$__range]))"
      }
     ]
    },
    {
     "title": "Sources Deleted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_sources_destroyed[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Topological API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(topological_inventory_api_rss)"
      }
     ]
    },
    {
     "title": "Requests / h",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 17, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(topological_inventory_api_http_requests_total{controller!=\"status\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[60m]) * 60 * 60)"
      }
     ]
    },
    {
     "title": "Request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) * 1000 > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Requests count / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Max Request Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
       "legendFormat": "Max Request"
      },
      {
       "expr": "max(rate(topological_inventory_api_http_sql_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_sql_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
       "legendFormat": "Max SQL"
      }
     ]
    },
    {
     "title": "Successful Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(topological_inventory_api_http_requests_total{status=~\"^[23].*\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Avg Requests Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
       "legendFormat": "Avg Request"
      },
      {
       "expr": "avg(rate(topological_inventory_api_http_sql_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_sql_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
       "legendFormat": "Avg SQL"
      }
     ]
    },
    {
     "title": "Error Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(topological_inventory_api_http_requests_total{status=~\"^[45].*\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "CPU Usage [1m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"topological-inventory-api\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"topological-inventory-api\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}