{
 "title": "Topological Inventory - APIs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller (Public API)",
    "query": "label_values(topological_inventory_api_http_requests_total,controller)"
   },
   {
    "name": "action",
    "label": "Action (Public API)",
    "query": "label_values(topological_inventory_api_http_requests_total{controller=~\"$controller\"},action)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Up",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "Restarts count / chosen range",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 4, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "Topological API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-api\"})"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-ingress-api\"})"
    }
   ]
  },
  {
   "title": "Topological API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-ingress-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Topological API Request Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Avg / Max Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max Request"
    },
    {
     "expr": "avg(rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg Request"
    },
    {
     "expr": "max(rate(topological_inventory_api_http_sql_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_sql_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max SQL"
    },
    {
     "expr": "avg(rate(topological_inventory_api_http_sql_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_sql_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg SQL"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(topological_inventory_api_http_duration_seconds_sum{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) * 1000 > 0",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Topological API Request Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_api_http_duration_seconds_count{controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Error Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(topological_inventory_api_http_requests_total{status=~\"^[45].*\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topological API CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"topological-inventory-api\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"topological-inventory-api\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "Ingress API Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Avg / Max Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(topological_inventory_ingress_api_http_duration_seconds_sum{controller!=\"status\"}[5m]) / rate(topological_inventory_ingress_api_http_duration_seconds_count{controller!=\"status\"}[5m]) > 0)",
     "legendFormat": "Max Request"
    },
    {
     "expr": "avg(rate(topological_inventory_ingress_api_http_duration_seconds_sum{controller!=\"status\"}[5m]) / rate(topological_inventory_ingress_api_http_duration_seconds_count{controller!=\"status\"}[5m]) > 0)",
     "legendFormat": "Avg Request"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(topological_inventory_ingress_api_http_duration_seconds_sum{controller!=\"status\"}[5m]) / rate(topological_inventory_ingress_api_http_duration_seconds_count{controller!=\"status\"}[5m]) * 1000 > 0",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Ingress API Request Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(topological_inventory_ingress_api_http_duration_seconds_count{controller!=\"status\"}[5m]) > 0",
       "legendFormat": "{{controller}}/{{action}}"
      }
     ]
    },
    {
     "title": "Error Requests / s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(topological_inventory_ingress_api_http_requests_total{status=~\"^[45].*\"}[5m])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress API CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"topological-inventory-ingress-api\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"topological-inventory-ingress-api\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS metrics [TODO]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  }
 ]
}