{
 "title": "Topological Inventory - Core",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "DatasourceRDS", "label": "Datasource (RDS)", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace (RDS)",
    "query": "topological-inventory-stage,topological-inventory-prod"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Up",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "Restarts count / chosen range",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "options": { "content": "\n\n" },
   "content": "\n\n"
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-api\"})"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-ingress-api\"})"
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-orchestrator\"})"
    }
   ]
  },
  {
   "title": "Persister",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-persister\"})"
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-sources-sync\"})"
    }
   ]
  },
  {
   "title": "Host Inv. Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"topological-inventory-host-inventory-sync\"})"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Ingress API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-ingress-api\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-orchestrator\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Persister",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-persister\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-sources-sync\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Host Inv. Sync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"topological-inventory-host-inventory-sync\"}[$__range])))"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=~\"topological-inventory-(persister|orchestrator|sources-sync|host-inventory-sync)\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"topological-inventory-(persister|orchestrator|sources-sync|host-inventory-sync)\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Kafka lag - Operations ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=~'platform.topological-inventory.operations-.*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "Kafka lag - !Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=~'platform.topological-inventory..*',topic!~'platform.topological-inventory.operations.*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "RDS Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS database connections average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_rds_database_connections_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "RDS CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_rds_cpuutilization_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "CPU utilization average"
      },
      {
       "expr": "sum(rdsosmetrics_cpuUtilization_total{exported_instance=\"$namespace\"})",
       "legendFormat": "OS Metrics Total Util"
      },
      {
       "expr": "sum(rdsosmetrics_cpuUtilization_system{exported_instance=\"$namespace\"})",
       "legendFormat": "OS Metrics System Util"
      }
     ]
    },
    {
     "title": "RDS storage space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_fileSys_total{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
       "legendFormat": "Storage total "
      },
      {
       "expr": "max(rdsosmetrics_fileSys_used{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
       "legendFormat": "Storage used"
      }
     ]
    },
    {
     "title": "RDS memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_memory_total{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory total"
      },
      {
       "expr": "max(rdsosmetrics_memory_free{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory free"
      },
      {
       "expr": "max(rdsosmetrics_memory_cached{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory cached"
      },
      {
       "expr": "max(rdsosmetrics_memory_buffers{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory buffers"
      },
      {
       "expr": "max(rdsosmetrics_memory_active{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory active"
      }
     ]
    },
    {
     "title": "RDS tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_tasks_sleeping{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks sleeping"
      },
      {
       "expr": "max(rdsosmetrics_tasks_running{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks running"
      },
      {
       "expr": "max(rdsosmetrics_tasks_blocked{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks blocked"
      },
      {
       "expr": "max(rdsosmetrics_tasks_stopped{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks stopped"
      },
      {
       "expr": "max(rdsosmetrics_tasks_total{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks total"
      },
      {
       "expr": "max(rdsosmetrics_tasks_zombie{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks zombie"
      }
     ]
    },
    {
     "title": "RDS DIsk IO util",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_diskIO_util{exported_instance=\"$namespace\"}) by (device)",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "RDS network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_network_rx{exported_instance=\"$namespace\"})",
       "legendFormat": "Network receive"
      },
      {
       "expr": "max(rdsosmetrics_network_tx{exported_instance=\"$namespace\"})",
       "legendFormat": "Network transmit"
      }
     ]
    },
    {
     "title": "RDS latency average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(aws_rds_read_latency_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Read Latency Average"
      },
      {
       "expr": "max(aws_rds_write_latency_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Write Latency Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Persister",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages  results",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_persister_messages_total[$__range])) by (result)",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Errors by type",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_persister_messages_total{result='error'}[$__range])) by (error_class)",
       "legendFormat": "{{error_class}}"
      }
     ]
    },
    {
     "title": "Msg processing duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(topological_inventory_persister_message_process_seconds_sum[5m]) / \nrate(topological_inventory_persister_message_process_seconds_count[5m]) > 0)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate (container_cpu_usage_seconds_total{container=\"topological-inventory-persister\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"topological-inventory-persister\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events count",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_orchestrator_events_count[$__range])) by (event_name)",
       "legendFormat": "{{event_name}}"
      }
     ]
    },
    {
     "title": "Collectors' OpenShift Resources",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 6, "x": 11, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topological_inventory_orchestrator_config_maps",
       "legendFormat": "{{source_type}}-ConfigMap"
      },
      {
       "expr": "topological_inventory_orchestrator_deployment_configs",
       "legendFormat": "{{source_type}}-DC"
      },
      {
       "expr": "topological_inventory_orchestrator_secrets",
       "legendFormat": "{{source_type}}-Secret"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_orchestrator_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sources Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    { "title": "Related to chosen range", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 } },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_errors_total[$__range]))"
      }
     ]
    },
    {
     "title": "Sources Created ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_sources_created[$__range]))"
      }
     ]
    },
    {
     "title": "Sources Deleted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(topological_inventory_sources_sync_sources_destroyed[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Inventory Sync [TODO]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  }
 ]
}