=begin
Topological Inventory

Topological Inventory

OpenAPI spec version: 0.0.1
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
module TopologicalInventory
  module Api
    class UsersController < ApplicationController
      def list_providers
        render json: Source.all
      end

      def list_container_projects
        render json: ContainerProject.all
      end

      def list_container_groups
        render json: ContainerGroup.all
      end

      def list_service_offerings
        render json: ServiceOffering.all
      end

      def list_service_parameters_sets
        render json: ServiceParametersSet.all
      end
    end
  end
end
