=begin
Topological Inventory

Topological Inventory

OpenAPI spec version: 0.0.1
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

module Legacy
class Provider < ApiRecord
  def initialize(options = {})
    @id = options['id']
    @href = options['href']
    @name = options['name']
    @type = options['type']
    @url = options['url']
    @verify_ssl = options['verify_ssl']
    @username   = options['username']
    @password   = options['password']
  end

  def self.all
    get_response(providers_url)['resources'].collect { |r| new(r) }
  end

  def self.create!(options = {})
    post_data(
      providers_create_url,
      "url"      => options['url'],
      "action"   => "create",
      "resource" => {
        "type"        => options["type"],
        "name"        => options['name'],
        "verify_ssl"  => options['verify_ssl'],
        "credentials" => {
          "userid"   => options['username'],
          "password" => options['password']
        }
      }
    )
  end

  def self.providers_url
    URI.join(api_url, "providers?expand=resources").to_s
  end

  def self.providers_create_url
    URI.join(api_url, "providers").to_s
  end

  def self.post_data(url, payload)
    result = RestClient::Request.new(
      :method     => :post,
      :url        => url,
      :user       => "admin",
      :password   => "smartvm",
      :payload    => payload.to_json,
      :verify_ssl => false
    ).execute
    JSON.parse(result.body)
  end
end
end