swagger: '2.0'
info:
  description: Topological Inventory
  version: 0.0.1
  title: Topological Inventory
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []

paths:
  /providers:
    get:
      tags:
      - users
      summary: List Providers
      operationId: listProviders
      description: |
        Returns an array of provider objects
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        200:
          description: Provider Info
          schema:
            type: array
            items:
              $ref: '#/definitions/Provider'
  /service_offerings:
    get:
      tags:
      - users
      summary: List ServiceOfferings
      operationId: listServiceOfferings
      description: Returns an array of ServiceOffering objects
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        200:
          description: ServiceOffering info
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceOffering'
  /service_parameters_sets:
    get:
      tags:
      - users
      summary: List ServiceParametersSets
      operationId: listServiceParametersSets
      description: Returns an array of ServiceParametersSet objects
      produces:
      - application/json
      consumes:
      - application/json
      responses:
        200:
          description: ServiceParametersSets info
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceParametersSet'

# define reusable parameters:
parameters:
  ProviderID:
    name: provider_id
    in: path
    description: The Provider ID
    required: true
    type: string
    format: uuid
  OptionalProviderID:
    name: provider_id
    in: query
    description: The Provider ID
    type: integer

# define reusable definitions
definitions:
  Provider:
    type: object
    required:
    - name
    - url
    - token
    properties:
      id:
        type: string
        readOnly: true
        format: uuid
      name:
        type: string
        example: Sample Provider
        title: Name
      description:
        type: string
        example: This is a sample description for a provider
        title: Description
      url:
        type: string
        format: url
        example: The REST API end point for the provider
        title: Provider URL
      user:
        type: string
        title: User
        description: The user used to connect to the provider
      password:
        type: string
        title: Password
        description: The password used to connect to the provider
      token:
        type: string
        title: Token
        description: The token used to connect to the provider
      verify_ssl:
        type: boolean
        default: true
        title: Verify Server Certificate
        description: Verify the servers certificate, you can disable it for servers with self signed certificates.
  ServiceOffering:
    type: object
    properties:
      id:
        type: string
        readOnly: true
        format: uuid
      name:
        type: string
        example: Sample Provider
        title: Name
      description:
        type: string
        example: This is a sample description for a provider
        title: Description
      ems_ref:
        type: string
        example: object-12345_67890
        title: EMS reference
        description: The native reference used by the EMS to refer to this object
      extra:
        type: object
        example: Extra information about this object in JSON format
        title: Extra
  ServiceParametersSet:
    type: object
    properties:
      id:
        type: string
        readOnly: true
        format: uuid
      name:
        type: string
        example: Sample Provider
        title: Name
      description:
        type: string
        example: This is a sample description for a provider
        title: Description
      ems_ref:
        type: string
        example: object-12345_67890
        title: EMS reference
        description: The native reference used by the EMS to refer to this object
      extra:
        type: object
        example: Extra information about this object in JSON format
        title: Extra

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
schemes:
 - https
 - http
basePath: /api/0.0
