=begin
Topological Inventory

Topological Inventory

OpenAPI spec version: 0.0.1
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do
  namespace :api do
    namespace :v0x0, :path => "v0.0" do
      resources :providers,               :only => [:index, :show]
      resources :service_offerings,       :only => [:index, :show]
      resources :service_parameters_sets, :only => [:index, :show]
    end
  end
end
