=begin
Topological Inventory

Topological Inventory

OpenAPI spec version: 0.0.1
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def list_providers
    render json: Provider.all
  end

  def list_service_offerings
    render json: ServiceOffering.all
  end

  def list_service_parameters_sets
    render json: ServiceParametersSet.all
  end
end
